language: python

python:
  - 2.7

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gcc-4.8
    - g++-4.8

before_install:
  # install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ -d $HOME/miniconda ]; then export PATH=$HOME/miniconda/bin:$PATH; fi
  - if [ -d $HOME/miniconda2 ]; then export PATH=$HOME/miniconda2/bin:$PATH; fi
  - echo $PATH
  - conda update --yes conda
  
  # configure compilers
  - export CC=gcc-4.8
  - export CXX=g++-4.8

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy matplotlib nose pandas scikit-bio scikit-learn pyparsing pyyaml six biopython
  - pip install .

sudo: false

script: nosetests
